/*
=============================================================
                Business Sales Analysis Queries
=============================================================

[!] Script Purpose:
    This script contains a collection of analytical SQL queries
    designed to extract business insights from the 'tickets'
    table within the 'sanoyfresco' database.

    The queries focus on analyzing sales performance,
    customer behavior, and product trends to support
    business decision-making.

    These queries demonstrate common data analysis
    techniques used in business intelligence and
    data analytics workflows.

[!] Main Table:
    dbo.tickets

[!] Analysis Topics Covered:

    1. Revenue Analysis
       • Total revenue generated by the business
       • Monthly revenue trends

    2. Sales Performance
       • Sales performance by department
       • Sales distribution across store sections

    3. Product Performance
       • Top 10 most sold products by quantity
       • Top 10 products generating the highest revenue

    4. Customer Analysis
       • Top 20 customers by total spending
       • Average purchase value per customer

    5. Order Metrics
       • Total number of orders
       • Average order value

[!] Key SQL Techniques Used:

    • Aggregations (SUM, AVG, COUNT)
    • GROUP BY analysis
    • Sorting and ranking (ORDER BY, TOP)
    • Subqueries for aggregated metrics
    • Date grouping for time-based analysis

[!] Execution Notes:

    • The queries assume the 'tickets' table contains
      transactional sales data including products,
      customers, prices, and dates.

    • These queries can be used as the foundation
      for dashboards or BI reports.

[!] Possible Use Cases:

    • Sales dashboards
    • Business performance monitoring
    • Customer segmentation
    • Product performance analysis
    • Revenue trend analysis
*/

USE sanoyfresco
GO

-- ¿Cuál es el ingreso total generado por el negocio?

SELECT TOP 100 fecha, ROUND(SUM(precio_total), 2) AS total_generado
FROM dbo.tickets;

-- ¿Cómo ha sido la tendencia de ingresos mensuales?

SELECT TOP 1000 FORMAT(fecha, 'yyyy-MM') AS sort_month_year, ROUND(SUM(precio_total), 2) AS total_generado
FROM dbo.tickets
GROUP BY sort_month_year
ORDER BY total_generado DESC;


-- ¿Cuál es el rendimiento de cada departamento en términos de ventas? tickets
SELECT id_departamento, ROUND(SUM(precio_total), 2) AS rendimiento_total
FROM dbo.tickets
GROUP BY id_departamento
ORDER BY rendimiento_total DESC;


-- ¿Cómo se distribuyen las ventas entre las diferentes secciones?
SELECT TOP 1000 id_seccion, ROUND(SUM(precio_total), 2) AS rendimiento_total
FROM dbo.tickets
GROUP BY id_seccion
ORDER BY rendimiento_total DESC;


-- ¿Cuáles son los 10 productos más vendidos en cantidad?
SELECT TOP 10 nombre_producto, ROUND(SUM(cantidad), 2) AS cantidad_total
FROM dbo.tickets
GROUP BY nombre_producto
ORDER BY cantidad_total DESC;


-- ¿Qué 10 productos generan más ingresos?
SELECT TOP 10 nombre_producto, ROUND(SUM(precio_total), 2) AS precio_total
FROM dbo.tickets
GROUP BY nombre_producto
ORDER BY precio_total DESC; 


-- ¿Quiénes son los 20 clientes que más compran en términos de ingresos?
SELECT TOP 20 id_cliente, ROUND(SUM(precio_total), 2) AS precio_total 
FROM dbo.tickets
GROUP BY id_cliente
ORDER BY precio_total DESC;


-- ¿Cuál es la compra media por cliente?
SELECT AVG(sum_precio_total) AS precio_ponderado
FROM (
	SELECT TOP 1000 id_cliente, SUM(precio_total) AS sum_precio_total
	FROM dbo.tickets
	GROUP BY id_cliente
) subquery;


-- ¿Cuántos pedidos totales se han realizado?
SELECT COUNT(DISTINCT id_cliente) AS pedidos_total
FROM dbo.tickets


-- ¿Cuál es el valor promedio por pedido?
SELECT TOP 100 ROUND(AVG(precio_total), 2) AS promedio_precio_total
FROM (
	SELECT id_pedido, SUM(precio_total) AS precio_total
	FROM dbo.tickets
	GROUP BY id_pedido
) subquery;